In [39]:
import numpy as np
a = np.array([[1, 6], [ 2, 8], [3, 11], [3, 10], [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [40]:
a.shape

(5, 2)

In [41]:
mean_a = np.mean(a, axis = 0)

In [42]:
mean_a

array([2. , 8.4])

In [43]:
a_centered = a - mean_a

In [44]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [45]:
a_centered.shape

(5, 2)

In [46]:
a_centered_sp = np.dot(a_centered[:,0],a_centered[:,1])
a_centered_sp

8.0

In [47]:
N = a.shape[0]

In [48]:
N

5

In [49]:
my_cov=a_centered_sp/(N-1)

In [50]:
my_cov

2.0

In [51]:
m = a.transpose()
m

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [52]:
x = np.cov(m)
x


array([[1. , 2. ],
       [2. , 4.3]])

In [53]:
if my_cov == x[0, 1]:
  print(True)

True
